"""current_state

Revision ID: b2d1de3b5082
Revises: d764fd87be23
Create Date: 2023-11-05 19:53:07.250326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b2d1de3b5082'
down_revision: Union[str, None] = 'd764fd87be23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'fecha_agregado',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('imagenes_productos', 'imagen',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)
    op.alter_column('usuario', 'nombre',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usuario', 'rol',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'rol',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('usuario', 'nombre',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('imagenes_productos', 'imagen',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)
    op.alter_column('cliente', 'fecha_agregado',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
