from schemas.productoSchema import ProductoPydantic, CantidadPydantic, ProductosIdPydantic, ProductoUpdatePydantic,ProductosCatPydantic, ProductosPedAggPydantic
from schemas.clienteSchema import ClientePydantic, ClienteEditarPydantic
from schemas.detallePedSchema import detallePedPydantic
from schemas.pedidoSchema import PedidoPydantic,valorPedPydantic,PedidoAggPydantic
from schemas.auth import UserLogin 