from schemas.productoSchema import ProductoPydantic, CantidadPydantic
from schemas.clienteSchema import ClientePydantic
from schemas.detallePedSchema import detallePedPydantic
from schemas.pedidoSchema import PedidoPydantic,valorPedPydantic